platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'Harness' do
    pod 'AFNetworking/NSURLSession', '~> 2.5.0'
    pod 'BDModules', :path => '../'
    pod 'FXKeychain', '~> 1.5.2'
    pod 'Snap', :git=> 'https://github.com/Masonry/Snap.git', :commit=> '4158cf0d9980d6b666f7736242423ac473c96800'
end

target 'HarnessTests' do
    pod 'BDModules', :path => '../'
end
