platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'Harness' do
    pod 'AFNetworking/NSURLSession', '~> 2.5.0'
    pod 'BDModules', :path => '../'
    pod 'FXKeychain', '~> 1.5.2'
    pod 'SDWebImage', '~>3.7.2'
    pod 'Snap', '~>0.9.2'
end

target 'HarnessTests' do
    pod 'BDModules', :path => '../'
end
